name: Build Windows Executable and Share

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyPDF2 pillow pyinstaller requests
        
    - name: Build executable
      run: python build_exe.py
      
    - name: Upload to transfer.sh
      run: |
        $downloadUrl = (curl -H "Max-Downloads: 10" -H "Max-Days: 5" --upload-file ./dist/PDF-Organizer.exe https://transfer.sh/PDF-Organizer.exe)
        echo "Download your executable from: $downloadUrl"
